version: "3.9"

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    ports:
      - "8080:80"
    volumes:
      - ../backend/:/opt/app/api
    networks:
      - app-network
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
