version: "3.9"

networks:
  app-network:
    driver: bridge

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    ports:
      - "8080:80"
    volumes:
      - ../src/:/opt/app/src
      - ../config/:/opt/app/config
    networks:
      - app-network
  redis:
    container_name: app_redis
    image: 'bitnami/redis:latest'
    platform: linux/amd64
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
